backend/controllers/CategoryController.php
<?php

namespace backend\controllers;

use common\components\UmemeTools;
use Yii;
use common\models\Category;
use common\models\CategorySearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CategoryController implements the CRUD actions for Category model.
 */
class CategoryController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function() {
                            return UmemeTools::isManager();
                        },
                    ],
                    // everything else is denied
                ],
            ],
        ];
    }

    /**
     * Lists all Category models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CategorySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Category model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Category model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($under = null)
    {
        $model = new Category();

        if ($model->load(Yii::$app->request->post())){
            if($under != null)
                $model->parent_id = $under;
            if($model->save()){}
                return $this->redirect(['view', 'id'=>$model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'parent'=>Category::findOne($under),
            ]);
        }
    }

    /**
     * Updates an existing Category model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Category model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Category model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Category the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Category::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }


}

backend/controllers/UserController.php
<?php

namespace backend\controllers;

use common\components\UmemeTools;
use common\models\Category;
use common\models\CategoryUser;
use frontend\models\SignupForm;
use Yii;
use common\models\User;
use app\models\UserSearch;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function() {
                            return UmemeTools::isManager();
                        },
                    ],
                    // everything else is denied
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $user = $this->findModel($id);
        $categoryUser = new CategoryUser();
        $categoryUser->user_id = $id;
        $subscribableCategories = Category::getCategoriesWithoutUser($user);
        $subscribedCategories = Category::getCategoriesWithUser($user);

        return $this->render('view', [
            'model' => $user,
            'categoryUser'=>$categoryUser,
            'subscribedCategories' => $subscribedCategories,
            'subscribableCategories' => $subscribableCategories,
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    /*public function actionCreate()
    {
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }*/



    public function actionCreate()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()){
                $user->guid = User::generateGUID();
                $user->save();
                $post = Yii::$app->request->post('SignupForm');
                $user->sendSignupEmail($post['password']);
                return $this->redirect(['/user/view', 'id'=>$user->id]);
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $post = Yii::$app->request->post();
        if ($model->load($post)) {
            $model->role = $post['User']['role'];
            if($model->save())
                return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionCategoriseUser(){
        $model = new CategoryUser();
        if(null != Yii::$app->request->post('CategoryUser')){
            $model->attributes = Yii::$app->request->post('CategoryUser');
            $model->save();
        }
        return $this->redirect(['/user/view', 'id'=>$model->user_id]);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionSetMissingGuids(){
        $users = User::find()->all();
        foreach($users as $user)
            if($user->guid == null)
                $user->updateGuid();
        echo 'OK';
    }

    public function actionResendLoginEmail($id){
        $user = $this->findModel($id);
        $user->sendLoginLink();
        return $this->redirect(['/user/view', 'id'=>$id]);
    }

    public function actionResetLoginLink($id){
        $user = $this->findModel($id);
        $user->updateGuid();
        return $this->redirect(['/user/view', 'id'=>$id]);
    }

    public function actionResetGuids(){
        $users = User::find()->all();
        foreach($users as $user)
            $user->updateGuid();
        return $this->redirect(['/user/index']);
    }

    public function actionRemoveFromCategory($category, $user)
    {
        CategoryUser::deleteAll([
            'category_id' => $category,
            'user_id' => $user,
        ]);
        return $this->redirect(['/user/view', 'id'=>$user]);
    }


    public function actionAccount(){

        $user = $this->findModel(Yii::$app->user->id);

        if (Yii::$app->request->post() != null){
            $user->username = $_POST['User']['username'];
            $user->email = $_POST['User']['email'];
            if($user->save())
                return $this->redirect(Url::home());
        }

        return $this->render('account', ['model'=>$user]);
    }

}

frontend/controllers/UserController.php
<?php

namespace frontend\controllers;

use common\models\Category;
use common\models\CategoryUser;
use frontend\models\SignupForm;
use Yii;
use common\models\User;
use app\models\UserSearch;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    // everything else is denied
                ],
            ],
        ];
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionAccount(){

        $user = $this->findModel(Yii::$app->user->id);

        if (Yii::$app->request->post() != null){
            $user->username = $_POST['User']['username'];
            $user->email = $_POST['User']['email'];
            if($user->save())
                return $this->redirect(Url::home());
        }
        $this->layout = 'column1';

        return $this->render('@backend/views/user/account', ['model'=>$user]);
    }
}

backend/views/user/_addToCategory.php
<?php
/**
 * Created by PhpStorm.
 * User: ronald
 * Date: 2/17/15
 * Time: 5:42 PM
 *  @var \common\models\CategoryUser $categoryUser
 *  @var array $categories
 */
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm; ?>

<div class="user-form ">

    <?php $form = ActiveForm::begin(['action'=>Url::to(['categorise-user'])]); ?>

    <div class="input-group form-inline">
        <?= $form->field($categoryUser, 'category_id')->dropDownList($categories, ['class'=>'form-control', 'style'=>'width:300px'])->label(false) ?>
        <div class="form-group input-group-btn">
            <?= Html::submitButton('Add to Category', ['class' => $categoryUser->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        </div>
    </div>

    <input type="hidden" id="categoryuser-user_id" class="form-control" name="CategoryUser[user_id]" value="<?=$categoryUser->user_id?>">

    <?php ActiveForm::end(); ?>

</div>
<style>
    div.field-groupuser-group_id{
        max-height: 34px;
    }
</style>

backend/views/user/_form.php
<?php

use common\models\User;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">

    <?php $form = ActiveForm::begin(); ?>

    <?php if($model->isNewRecord)
        echo $form->field($model, 'username')->textInput() ?>

    <?= $form->field($model, 'email')->textInput() ?>

    <?= $form->field($model, 'role')->dropDownList(User::getRoleEnumList(),['class'=>'form-control']) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'auth_key') ?>

    <?= $form->field($model, 'password_hash') ?>

    <?= $form->field($model, 'password_reset_token') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'role') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/user/_userForm.php
<?php

use common\models\User;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'username')->textInput() ?>

    <?= $form->field($model, 'email')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/user/account.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = 'Update your data' ;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->username, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="user-update">

    <h3><?= Html::encode($this->title) ?></h3>

    <?= $this->render('@backend/views/user/_userForm', [
        'model' => $model,
    ]) ?>

</div>

backend/views/user/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = 'Create User';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="panel user-panel">
    <div class="panel-body">
        <div class="user-create">

            <h2><?= Html::encode($this->title) ?></h2>

            <?= $this->render('_form', [
                'model' => $model,
            ]) ?>

        </div>
    </div>
</div>

backend/views/user/index.php
<?php

use common\models\User;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Users';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="panel user-panel">
    <div class="panel-body">
        <div class="user-index">

            <h2><?= Html::encode($this->title) ?></h2>
            <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

            <p>
                <?= Html::a('Create User', ['create'], ['class' => 'btn btn-success']) ?>
                <?= Html::a('Reset Login Links', ['reset-guids'], ['class' => 'btn btn-default']) ?>
            </p>

            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],
                    //'id',
                    [
                        'label'=>'username',
                        'attribute'=>'username',
                        'format'=>'raw',
                        'value'=>function($data){
                            return Html::a($data->username,['view', 'id'=>$data->id]);
                        }
                    ],
                    //'auth_key',
                    //'password_hash',
                    //'password_reset_token',
                    'email:email',
                    'status',
                    // 'created_at',
                    // 'updated_at',
                    [
                        'label'=>'role',
                        'attribute'=>'role',
                        'filter'=>Html::activeDropDownList($searchModel, 'role', User::getRoleEnumList(),['class'=>'form-control'])
                    ],

                    ['class' => 'yii\grid\ActionColumn'],
                ],
            ]); ?>

        </div>
    </div>
</div>

backend/views/user/signup.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

$this->title = 'New User';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="panel user-panel">
    <div class="panel-body">
        <div class="site-signup">
            <h2><?= Html::encode($this->title) ?></h2>

            <p>Please fill out the following fields :</p>

            <div class="row">
                <div class="col-lg-5">
                    <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>
                    <?= $form->field($model, 'username') ?>
                    <?= $form->field($model, 'email') ?>
                    <?= $form->field($model, 'password')->passwordInput() ?>
                    <div class="form-group">
                        <?= Html::submitButton('Create User', ['class' => 'btn btn-success', 'name' => 'signup-button']) ?>
                    </div>
                    <?php ActiveForm::end(); ?>
                </div>
            </div>
        </div>
    </div>
</div>

backend/views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = 'Update  ' . $model->username. ((substr($model->username, -1) != 's')?"'s":"'").' data' ;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="panel user-panel">
    <div class="panel-body">
        <div class="user-update">

            <h3><?= Html::encode($this->title) ?></h3>

            <?= $this->render('_form', [
                'model' => $model,
            ]) ?>

        </div>
    </div>
</div>

backend/views/user/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\User */
/* @var $categoryUser common\models\CategoryUser */
/* @var $subscribableCategories array */
/* @var $subscribedCategories array */

$this->title = $model->getName();
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="panel user-panel">
    <div class="panel-body">
        <div class="user-view" xmlns="http://www.w3.org/1999/html">

            <h1><?= Html::encode($this->title) ?></h1>

            <p>
                <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-sm btn-primary']) ?>
                <?= Html::a('Delete', ['delete', 'id' => $model->id], [
                    'class' => 'btn btn-danger btn-sm',
                    'data' => [
                        'confirm' => 'Are you sure you want to delete this item?',
                        'method' => 'post',
                    ],
                ]) ?>
                <?= Html::a('Reset Login Link', ['reset-login-link', 'id' => $model->id], ['class' => 'btn btn-sm btn-default']) ?>
                <?= Html::a('Resend Login Link via Email', ['resend-login-email', 'id' => $model->id], ['class' => 'btn btn-sm btn-default']) ?>
            </p>

            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    //'id',
                    'username',
                    //'auth_key',
                    //'password_hash',
                    //'password_reset_token',
                    'email:email',
                    //'status',
                    //'created_at',
                    //'updated_at',
                    'role',
                    //['label'=>'Login Url', 'value'=>$model->getLoginLink()]
                ],
            ]) ?>

            <div class="panel user-category">

                <div class="panel-body">
                    <div>
                        <?php if(count($subscribableCategories) > 0):?>
                            <h4><?=$model->getName()?> can be added to the following categories</h4>
                            <?= Yii::$app->controller->renderPartial('_addToCategory', [
                                'categoryUser'=>$categoryUser,
                                'categories'=>$subscribableCategories
                            ])?><br>
                        <?php endif?>
                    </div>

                    <?php if(count($subscribedCategories) > 0):?>
                        <p><?=$model->getName()?> belongs to the following categories</p>
                        <ul class="list-group user-categories">
                            <?php foreach($subscribedCategories as $id => $category):?>
                                <li class="list-group-item">
                                    <span><?=Html::a('<i class="glyphicon glyphicon-trash"></i>', ['remove-from-category', 'category'=>$id, 'user'=>$model->id], ['class'=>'button', 'confirm'=>'Are you sure?'])?></span>
                                    <span><?=Html::a($category, ['category/view', 'id'=>$id])?></span>
                                </li>
                            <?php endforeach?>
                        </ul>
                    <?php endif?>
                </div>
            </div>

        </div>
    </div>
</div>