backend/controllers/TopicController.php
<?php

namespace backend\controllers;

use common\components\UmemeTools;
use common\models\TopicPost;
use Yii;
use common\models\Topic;
use common\models\TopicSearch;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TopicController implements the CRUD actions for Topic model.
 */
class TopicController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function() {
                            return UmemeTools::isManager();
                        },
                    ],
                    // everything else is denied
                ],
            ],
        ];
    }

    /**
     * Lists all Topic models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TopicSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Topic model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Topic model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Topic();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Topic model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Topic model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionApprove($id, $back){
        $post = TopicPost::findOne($id);
        $post->approved = 1;
        $post->update();
        return $this->redirect(['view', 'id'=>$back]);
    }

    /**
     * Finds the Topic model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Topic the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Topic::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionPost(){
        $model = new TopicPost();
        if(null != Yii::$app->request->post('TopicPost'))
            $model->saveNewPost(Yii::$app->request->post('TopicPost'), 1);

        return $this->redirect(Url::home());
    }
}

backend/controllers/UserController.php
<?php

namespace backend\controllers;

use common\components\UmemeTools;
use common\models\Category;
use common\models\CategoryUser;
use frontend\models\SignupForm;
use Yii;
use common\models\User;
use app\models\UserSearch;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function() {
                            return UmemeTools::isManager();
                        },
                    ],
                    // everything else is denied
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $user = $this->findModel($id);
        $categoryUser = new CategoryUser();
        $categoryUser->user_id = $id;
        $subscribableCategories = Category::getCategoriesWithoutUser($user);
        $subscribedCategories = Category::getCategoriesWithUser($user);

        return $this->render('view', [
            'model' => $user,
            'categoryUser'=>$categoryUser,
            'subscribedCategories' => $subscribedCategories,
            'subscribableCategories' => $subscribableCategories,
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    /*public function actionCreate()
    {
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }*/



    public function actionCreate()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()){
                $user->guid = User::generateGUID();
                $user->save();
                $post = Yii::$app->request->post('SignupForm');
                $user->sendSignupEmail($post['password']);
                return $this->redirect(['/user/view', 'id'=>$user->id]);
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $post = Yii::$app->request->post();
        if ($model->load($post)) {
            $model->role = $post['User']['role'];
            if($model->save())
                return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionCategoriseUser(){
        $model = new CategoryUser();
        if(null != Yii::$app->request->post('CategoryUser')){
            $model->attributes = Yii::$app->request->post('CategoryUser');
            $model->save();
        }
        return $this->redirect(['/user/view', 'id'=>$model->user_id]);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionSetMissingGuids(){
        $users = User::find()->all();
        foreach($users as $user)
            if($user->guid == null)
                $user->updateGuid();
        echo 'OK';
    }

    public function actionResendLoginEmail($id){
        $user = $this->findModel($id);
        $user->sendLoginLink();
        return $this->redirect(['/user/view', 'id'=>$id]);
    }

    public function actionResetLoginLink($id){
        $user = $this->findModel($id);
        $user->updateGuid();
        return $this->redirect(['/user/view', 'id'=>$id]);
    }

    public function actionResetGuids(){
        $users = User::find()->all();
        foreach($users as $user)
            $user->updateGuid();
        return $this->redirect(['/user/index']);
    }

    public function actionRemoveFromCategory($category, $user)
    {
        CategoryUser::deleteAll([
            'category_id' => $category,
            'user_id' => $user,
        ]);
        return $this->redirect(['/user/view', 'id'=>$user]);
    }


    public function actionAccount(){

        $user = $this->findModel(Yii::$app->user->id);

        if (Yii::$app->request->post() != null){
            $user->username = $_POST['User']['username'];
            $user->email = $_POST['User']['email'];
            if($user->save())
                return $this->redirect(Url::home());
        }

        return $this->render('account', ['model'=>$user]);
    }

}

frontend/views/layouts/column1.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);
$isLoggedIn = (!Yii::$app->user->isGuest);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
    <?php $this->beginBody() ?>
    <div class="wrap">
        <?php
            NavBar::begin([
                'brandLabel' => Html::img(Yii::$app->request->baseUrl.'/img/logo.png', ['style'=>'height:30px; display:inline']).' Umeme Academy Online',
                'brandUrl' => Yii::$app->homeUrl,
                'options' => [
                    'class' => 'navbar-inverse navbar-fixed-top',
                ],
            ]);
            $menuItems = [
                ['label' => 'Home', 'url' => ['/topic/index']],
            ];
            if($isLoggedIn && (Yii::$app->session->get('user.role') == 'manager'))
                $menuItems[] = ['label' => 'Admin', 'url' => '/admin'];
            if (Yii::$app->user->isGuest) {
                $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
            } else {
                $menuItems[] = [
                    'label' => 'Logout (' . Yii::$app->user->identity->username . ')',
                    'url' => ['/site/logout'],
                    'linkOptions' => ['data-method' => 'post']
                ];
            }
            echo Nav::widget([
                'options' => ['class' => 'navbar-nav navbar-right'],
                'items' => $menuItems,
            ]);
            NavBar::end();
        ?>

        <div class="container">
            <?= Breadcrumbs::widget([
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]) ?>
            <?php $navs = [
                ['Topics', 'topic'], ['Users', 'user'], ['Categories', 'category']
            ]?>
            <div class="site-index">
                <nav class="nav">
                    <ul class="nav nav-pills">
                        <?php
/*                        if($isLoggedIn)
                            foreach($navs as $nav):*/?><!--
                                <?php /*$style = ((Yii::$app->controller->id == $nav[1])?['class'=>'btn btn-default']:[])*/?>
                                <li><?/*= Html::a($nav[0], ['/'.$nav[1]], $style)*/?></li>
                            --><?php /*endforeach*/?>
                    </ul>
                </nav><hr>

                <div class="body-content">

                    <div class="row">
                        <div class="col-lg-2 sidebar">

                        </div>
                        <div class="col-lg-7">
                            <?= $content ?>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <footer class="footer">
        <div class="container">
        <p class="pull-left">&copy; Umeme <?= date('Y') ?></p>
        </div>
    </footer>
    <style>
        div.container div.navbar-header{
            background-color: #241e20;
        }
        .btn-success{
            background-color: #99b93b;
            border-color: #5cb85c;
        }
        a{
            color: #5cb85c;
        }
        a.hover, a.focus{
            color: #99b93b;
        }
        .navbar-inverse .navbar-nav > li > a:hover, a.navbar-brand:hover {
            color: #99b93b;
        }
        span.badge{
            background-color: #99b93b;
        }
        div.topic-view div.panel-group div.panel div.panel-heading{
            color: #58af58;
            background-color: #e2f4af;
            border-color: #5cb85c;
        }
    </style>
    <?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

frontend/views/layouts/main.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);
\common\components\UmemeTools::validateSession();
$isLoggedIn = (!Yii::$app->user->isGuest);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
    <?php $this->beginBody() ?>
    <div class="wrap">
        <?php
            NavBar::begin([
                'brandLabel' => Html::img(Yii::$app->request->baseUrl.'/img/logo.png', ['style'=>'height:30px; display:inline']).' Umeme Academy Online',
                'brandUrl' => Yii::$app->homeUrl,
                'options' => [
                    'class' => 'navbar-inverse navbar-fixed-top',
                ],
            ]);
            $menuItems = [
                ['label' => 'Home', 'url' => ['/topic/index']],
            ];
            if($isLoggedIn && (Yii::$app->session->get('user.role') == 'manager'))
                $menuItems[] = ['label' => 'Admin', 'url' => 'http://admin.'.$_SERVER['SERVER_NAME'] . '/site/login?uid=' . Yii::$app->session->get('user.guid')];
            if (Yii::$app->user->isGuest) {
                $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
            } else {
                $menuItems[] = [
                    'label' => 'Hi ' . Yii::$app->user->identity->username ,
                    'items' => [
                        ['label'=>'Account', 'url' => ['/user/account']],
                        ['label'=>'Logout', 'url' => ['/site/logout'], 'linkOptions' => ['data-method' => 'post']],
                    ]
                ];
            }
            echo Nav::widget([
                'options' => ['class' => 'navbar-nav navbar-right'],
                'items' => $menuItems,
            ]);
            NavBar::end();
        ?>

        <div class="container">
            <?= Breadcrumbs::widget([
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]) ?>
            <?php $navs = [
                ['Topics', 'topic'], ['Users', 'user'], ['Categories', 'category']
            ]?>
            <div class="site-index">
                <nav class="nav">
                    <ul class="nav nav-pills">
                        <h4>Hello <?=ucwords(implode(' ', explode('.', Yii::$app->user->identity->username)))?></h4>
                        <?php
                        /*if($isLoggedIn)
                            foreach($navs as $nav):*/?><!--
                                <?php /*$style = ((Yii::$app->controller->id == $nav[1])?['class'=>'btn btn-default']:[])*/?>
                                <li><?/*= Html::a($nav[0], ['/'.$nav[1]], $style)*/?></li>
                            --><?php /*endforeach*/?>
                    </ul>
                </nav><hr>

                <div class="body-content">

                    <div class="row">
                        <div class="col-lg-2 sidebar user-menu">
                            <?php if($isLoggedIn):?>
                                <?= Yii::$app->controller->renderPartial('@app/views/category/categories',[])?>
                            <?php endif?>
                        </div>
                        <div class="col-lg-3 sidebar user-menu" >
                            <?php if($isLoggedIn):?>
                                <?= Yii::$app->controller->renderPartial('@app/views/topic/topics',[])?>
                            <?php endif?>
                        </div>
                        <div class="col-lg-7">
                            <?= $content ?>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <footer class="footer">
        <div class="container">
        <p>
            <span class="pull-right"><?=Html::a('Managing Director\'s Statement', '#', [
                    'data-toggle'=>'modal',
                    'data-target'=>'#chairman-statement',
                ])?></span>
            <span class="pull-left">&copy; Umeme Academy <?= date('Y') ?></span>
        </p>
        </div>
    </footer>


    <!-- Modal -->
    <div class="modal fade " id="chairman-statement" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <?=Yii::$app->controller->renderPartial('@app/views/site/md-statement')?>
    </div>

    <?php $this->endBody() ?>

    <?php if(Yii::$app->session->hasFlash('loggedIn')):?>
        <?php Yii::$app->session->removeFlash('loggedIn')?>
    <script>
        $(document).ready(function () {
            $('#chairman-statement').modal('show');
        });
    </script>
    <?php endif?>
</body>
</html>
<?php $this->endPage() ?>