common/models/Topic.php
<?php

namespace common\models;

use Yii;
use yii\db\Expression;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "topic".
 *
 * @property integer $id
 * @property string $subject
 * @property string $created_on
 * @property integer $created_by
 * @property integer $category_id
 * @property integer $approved
 *
 * @property Category $category
 * @property User $createdBy
 * @property TopicPost[] $topicPosts
 */
class Topic extends \yii\db\ActiveRecord
{
    public static $active;
    private static $topics;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'topic';
    }

    public static function getPendingTopics()
    {
        $topics = self::getTopics();
        return $topics['pending'];
    }

    private static function populateTopics()
    {
        self::$topics = ['pending'=>[],'approved'=>[]];
        $command = "select count(p.id) as count, t.id as topic_id, t.subject as topic, p.approved as status from topic_post p, topic t where t.id = p.topic_id group by p.topic_id, p.approved";
        $result = Yii::$app->db->createCommand($command)->queryAll();
        if(count($result) > 0){
            $status = [0=>'pending',1=>'approved'];
            foreach($result as $row)
                self::$topics[$status[$row['status']]][] = [
                    'topic'=>$row['topic'],
                    'id'=>$row['topic_id'],
                    'count'=>$row['count']
                ];
        }
    }

    public static function getTopics(){
        if(!isset(self::$topics['pending']))
            self::populateTopics();
        return self::$topics;
    }

    public static function getApprovedTopics()
    {
        $topics = self::getTopics();
        return $topics['approved'];
    }

    public static function getTopicsInCategory($categoryId){
        $topicsArray = [];
        $topics = Topic::find()->where(['category_id'=>$categoryId])->all();
        if(count($topics) > 0)
            foreach ($topics as $topic)
                $topicsArray[] =  [
                    'topic'=>$topic->subject,
                    'id'=>$topic->id,
                    'count'=>count($topic->topicPosts),
                    'category_id'=>$categoryId
                ];
        return $topicsArray;
    }

    public static function getUserTopics($id)
    {
        if(!isset(self::$topics['user'][$id])){
            self::$topics['user'][$id] = [];
            $user = User::findIdentity($id);
            $categories = Category::getCategoriesWithUser($user);
            $categoryIds = implode(',', array_keys($categories));
            if($categoryIds){
                $command = "select count(p.id) as count, t.id as topic_id, t.subject as topic, p.approved as status from topic_post p, topic t where t.id = p.topic_id AND t.category_id in ({$categoryIds}) and p.approved = 1 group by p.topic_id, p.approved";
                $result = Yii::$app->db->createCommand($command)->queryAll();
                if(count($result) > 0){
                    foreach($result as $row)
                        self::$topics['user'][$id][] = [
                            'topic'=>$row['topic'],
                            'id'=>$row['topic_id'],
                            'count'=>$row['count']
                        ];
                }
            }
        }
        return self::$topics['user'][$id];
    }

    public static function getNewTopics()
    {
        $data = Topic::find()->asArray()->all();
        $topics =[];
        if(count($data) > 0){
            foreach($data as $topic)
                $topics[] = [
                    'topic'=>$topic['subject'],
                    'id'=>$topic['id'],
                ];
        }
        return $topics;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['created_on'], 'safe'],
            [['created_by', 'category_id'], 'integer'],
            [['subject'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'subject' => 'Subject',
            'created_on' => 'Created On',
            'created_by' => 'Created By',
            'category_id' => 'Category ID',
        ];
    }



    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTopicPosts()
    {
        return $this->hasMany(TopicPost::className(), ['topic_id' => 'id']);
    }

    public function beforeSave($insert){
        if (parent::beforeSave($insert)) {

            if($this->isNewRecord){
                $this->created_by = Yii::$app->user->id;
                $this->created_on = new Expression('CURRENT_TIMESTAMP');
            }
            return true;
        } else {
            return false;
        }
    }

    public function beforeDelete()
    {
        if (parent::beforeDelete()) {
            Yii::$app->db->createCommand("DELETE FROM topic_post WHERE topic_id = '{$this->id}'")->execute();
            return true;
        } else {
            return false;
        }
    }
}

backend/controllers/TopicController.php
<?php

namespace backend\controllers;

use common\components\UmemeTools;
use common\models\TopicPost;
use Yii;
use common\models\Topic;
use common\models\TopicSearch;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TopicController implements the CRUD actions for Topic model.
 */
class TopicController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function() {
                            return UmemeTools::isManager();
                        },
                    ],
                    // everything else is denied
                ],
            ],
        ];
    }

    /**
     * Lists all Topic models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TopicSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Topic model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Topic model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Topic();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Topic model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Topic model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionApprove($id, $back){
        $post = TopicPost::findOne($id);
        $post->approved = 1;
        $post->update();
        return $this->redirect(['view', 'id'=>$back]);
    }

    /**
     * Finds the Topic model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Topic the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Topic::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionPost(){
        $model = new TopicPost();
        if(null != Yii::$app->request->post('TopicPost'))
            $model->saveNewPost(Yii::$app->request->post('TopicPost'), 1);

        return $this->redirect(Url::home());
    }
}

frontend/controllers/TopicController.php
<?php

namespace frontend\controllers;

use common\components\UmemeTools;
use common\models\Category;
use common\models\CategoryUser;
use common\models\Group;
use common\models\TopicPost;
use common\models\User;
use Yii;
use common\models\Topic;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\MethodNotAllowedHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TopicController implements the CRUD actions for Topic model.
 */
class TopicController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'approve' => ['post']
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function() {
                            return UmemeTools::isLoggedIn();
                        },
                    ],
                    // everything else is denied
                ],
            ],
        ];
    }

    /**
     * Lists all Topic models.
     * @return mixed
     * @throws ForbiddenHttpException
     */
    public function actionIndex()
    {

        $categoryId = Yii::$app->request->get('cat');
        $topicId = Yii::$app->request->get('top');
        $category = null;

        if($categoryId != null && !Category::userCanSeeCategory(Yii::$app->user->id, $categoryId))
            throw new ForbiddenHttpException('You shouldn\'t see topics this category');

        if(!is_numeric($categoryId)){
            $user = User::findOne(Yii::$app->user->id);
            $categories = $user->getCategories();
            if(count($categories) > 0)
                $category = $categories[0];
        }else
            $category = Category::findOne($categoryId);

        Category::$active = $category->id;

        if($category != null && (count($category->topics) > 0)){
            $topics = ArrayHelper::map($category->topics, 'id', 'subject');
            if(($topicId == null) && count($category->topics) > 0)
                return $this->actionView($category->topics[0]->id);
            elseif(isset($topics[$topicId]))
                return $this->actionView($topicId);
        }
        return $this->render('no_topics');

    }

    /**
     * Displays a single Topic model.
     * @param $topicId
     * @return mixed
     * @throws ForbiddenHttpException
     * @throws NotFoundHttpException
     */
    public function actionView($topicId)
    {
        $topic = $this->findModel($topicId);
        Topic::$active = $topicId;

        if($topic == null)
            return $this->render('no_topics');
        else
            return $this->render('view', [
                'model' => $topic,
            ]);
    }

    /**
     * Finds the Topic model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Topic the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Topic::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionPost(){
        $model = new TopicPost();
        if(null != Yii::$app->request->post('TopicPost'))
            $model->saveNewPost(Yii::$app->request->post('TopicPost'));

        return $this->redirect(Url::home());
    }
}

frontend/controllers/UserController.php
<?php

namespace frontend\controllers;

use common\models\Category;
use common\models\CategoryUser;
use frontend\models\SignupForm;
use Yii;
use common\models\User;
use app\models\UserSearch;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    // everything else is denied
                ],
            ],
        ];
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionAccount(){

        $user = $this->findModel(Yii::$app->user->id);

        if (Yii::$app->request->post() != null){
            $user->username = $_POST['User']['username'];
            $user->email = $_POST['User']['email'];
            if($user->save())
                return $this->redirect(Url::home());
        }
        $this->layout = 'column1';

        return $this->render('@backend/views/user/account', ['model'=>$user]);
    }
}

frontend/views/topic/_form.php
<?php

use common\models\Category;
use common\models\Group;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Topic */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="topic-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'subject')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'category_id')->dropDownList(ArrayHelper::merge([''=>'None'],ArrayHelper::map(Category::find()->all(),'id', 'name')))->label('Category') ?>

    <?= $form->field($model, 'group_id')->dropDownList(ArrayHelper::merge([''=>'None'],ArrayHelper::map(Group::find()->all(),'id', 'name')))->label('Group') ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/topic/_newPost.php
<?php
/**
 * Created by PhpStorm.
 * User: ronald
 * Date: 2/18/15
 * Time: 3:01 PM
 * @var \common\models\TopicPost $model
 * @var integer $topic_id
 */
use vova07\imperavi\Widget;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
$model->author_id = Yii::$app->user->id;
if(!isset($placeholder)) $placeholder = 'Write your opinion here . . .';
$model->topic_id = $topic_id;?>
<div class="post-form form">

    <?php $form = ActiveForm::begin(['action'=>Url::to(['/topic/post'])]); ?>

    <?=$form->field($model, 'content')->widget(Widget::className(), [
        'settings' => [
            'lang' => 'en',
            'minHeight' => 130,
            'placeholder'=>$placeholder,
            'plugins' => [
                /*'clips',*/'fullscreen','video',
            ]
        ]
    ])->label('')?>

    <div class="form-group">
        <?= Html::submitButton('Post', ['class' => ($model->isNewRecord ? 'btn btn-success' : 'btn btn-primary') . ' pull-right']) ?>
    </div>

    <?= $form->field($model, 'author_id')->hiddenInput()->label('') ?>
    <?= $form->field($model, 'topic_id')->hiddenInput()->label('') ?>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/topic/_post.php
<?php
/**
 * Created by PhpStorm.
 * User: ronald
 * Date: 2/17/15
 * Time: 2:29 PM
 * @var \common\models\TopicPost $post
 * @var \yii\i18n\Formatter $formatter
 */?>
<div class="panel panel-default">
    <div class="panel-heading" role="tab" id="postHeading<?= $post->id ?>">
        <h4 class="panel-title">
            <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#post<?= $post->id ?>" aria-expanded="true" aria-controls="post<?= $post->id ?>">
                <?= $post->author->username?>
                <span style="font-size: 12px" class="pull-right"><?= $formatter->asDatetime($post->posted_on, 'php:d F Y H:i:s A')?></span>
            </a>
        </h4>
    </div>
    <div id="post<?= $post->id ?>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="postHeading<?= $post->id ?>">
        <div class="panel-body">
            <?= $post->content?>
            <hr>
            <p>
                <i style="font-size: 12px">
                    posted on <?= $formatter->asDatetime($post->posted_on, 'php:d F Y H:i:s A')?>
                </i>
                <?php if($post->approved == 0)
                    \yii\helpers\Html::a('<span><i class="glyphicon glyphicon-check"></i> Approve</span>', ['approve', 'id'=>$post->id, 'back'=>$post->topic_id], ['class'=>'btn pull-right', 'data-method'=>'post', 'style'=>'color:green'])?>
            </p>
        </div>
    </div>
</div>

frontend/views/topic/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\TopicSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="topic-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'subject') ?>

    <?= $form->field($model, 'created_on') ?>

    <?= $form->field($model, 'created_by') ?>

    <?= $form->field($model, 'category_id') ?>

    <?php // echo $form->field($model, 'group_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/topic/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Topic */

$this->title = 'Create Topic';
$this->params['breadcrumbs'][] = ['label' => 'Topics', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="topic-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/topic/index.php
<?php

use common\models\Category;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\i18n\Formatter;

/* @var $this yii\web\View */
/* @var $searchModel common\models\TopicSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Topics';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="topic-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Topic', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            //'id',
            [
                'label'=>'Topic',
                'attribute'=>'subject',
                'format'=>'raw',
                'value'=>function($data){
                    return Html::a($data->subject, ['/topic/view', 'id'=>$data->id]);
                 }
            ],
            [
                'label'=>'Created On',
                'attribute'=>'created_on',
                'value'=>'created_on',
            ],
            [
                'attribute'=>'category_id',
                'filter'=>Html::activeDropDownList($searchModel, 'category_id', ArrayHelper::merge([''=>'Any'],ArrayHelper::map(Category::find()->all(),'id', 'name')),['class'=>'form-control'])
            ],
            [
                'label'=>'Created By',
                //'attribute'=>'created_by',
                'format'=>'raw',
                'value'=>function($data){
                        $user = \common\models\User::findOne($data->created_by);
                        return Html::a($user->username, ['/user/view', 'id'=>$data->id]);
                }
            ],
            // 'group_id',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>

frontend/views/topic/no_topics.php
<?php
/**
 * Created by PhpStorm.
 * User: ronald
 * Date: 2/18/15
 * Time: 2:39 PM
 */
$this->title = 'No Topics';
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="topic-index">

    <h4>There are no topics at the moment</h4>

</div>

frontend/views/topic/topics.php
<?php
/**
 * Created by PhpStorm.
 * User: Ronald
 * Date: 2/16/15
 * Time: 4:53 PM
 */
use common\models\Category;
use common\models\Topic;
use yii\helpers\Html;?>

<?php $topics  = Topic::getTopicsInCategory(Category::$active);?>

    <h4 class="topic-heading">Topics</h4>
    <?php if(count($topics) > 0){
            printTopics($topics);
          }else{?>
            <ul class="nav nav-sidebar">
                <li><?= Html::a("There are no topics at the moment")?></li>
            </ul>
         <?php }?>

    <?php function printTopics($topics, $showBadge = false){?>
        <ul class="nav nav-sidebar">
            <?php foreach($topics as $topic):?>
                <?php $badge = ($showBadge?"<span class='badge badge-success'>{$topic['count'] }</span>":'')?>
                <li <?= ((Topic::$active == $topic['id']) ?'class="active"' :'') ?>>
                    <?= Html::a("{$topic['topic']} $badge", ['/topic/index', 'cat'=>$topic['category_id'], 'top'=>$topic['id']])?>
                </li>
            <?php endforeach?>
        </ul>
    <?php } ?>

frontend/views/topic/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Topic */

$this->title = 'Update Topic: ' . ' ' . $model->subject;
$this->params['breadcrumbs'][] = ['label' => 'Topics', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="topic-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/topic/view.php
<?php

use common\models\TopicPost;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Topic */

$this->title = $model->subject;
$this->params['breadcrumbs'][] = ['label' => 'Topics', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="topic-view">

    <h3><?= Html::encode($this->title) ?></h3>

    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <?php if(isset($model->topicPosts) && (count($model->topicPosts) > 0)){
            $formatter = new \yii\i18n\Formatter();
            $collapseId=-1;
            foreach($model->topicPosts as $post){
                if(($post->approved == 1) || ($post->author_id = Yii::$app->user->id)){
                    $collapseId = $post->id;
                    echo Yii::$app->controller->renderPartial('@app/views/topic/_post', ['post'=>$post, 'formatter'=>$formatter]);
                }
            }?>
            <?php if($collapseId == -1) $collapseId=$post->id;?>
            <script type="application/javascript">
                var lastPostId = 'post<?= $collapseId ?>';
                var lastPost = document.getElementById(lastPostId);
                lastPost.classList.add('in');
                window.location = '#' + lastPostId;
            </script>
        <?php } ?>
        <?= Yii::$app->controller->renderPartial('_newPost',[
            'model'=>new TopicPost(),
            'topic_id'=>$model->id,
        ])?>
    </div>
</div>